#!/bin/bash
export ADMIN_PASS=$1
export CINDER_DBPASS=$ADMIN_PASS
export CINDER_PASS=$ADMIN_PASS
export DASH_DBPASS=$ADMIN_PASS
export DEMO_PASS=$ADMIN_PASS
export GLANCE_DBPASS=$ADMIN_PASS
export GLANCE_PASS=$ADMIN_PASS
export KEYSTONE_DBPASS=$ADMIN_PASS
export METADATA_SECRET=$ADMIN_PASS
export NEUTRON_DBPASS=$ADMIN_PASS
export NEUTRON_PASS=$ADMIN_PASS
export NOVA_DBPASS=$ADMIN_PASS
export NOVA_PASS=$ADMIN_PASS
export PLACEMENT_PASS=$ADMIN_PASS
export RABBIT_PASS=$ADMIN_PASS

echo $CINDER_DBPASS
echo $CINDER_PASS
echo $DASH_DBPASS
echo $DEMO_PASS
echo $GLANCE_DBPASS
echo $GLANCE_PASS
echo $KEYSTONE_DBPASS
echo $METADATA_SECRET
echo $NEUTRON_DBPASS
echo $NEUTRON_PASS
echo $NOVA_DBPASS
echo $NOVA_PASS
echo $PLACEMENT_PASS
echo $RABBIT_PASS

export MGMT_IP=$2
